project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN
base_path: .
files:
  - source: /locales/en/LC_MESSAGES/seasons.po
    translation: /locales/%two_letters_code%/LC_MESSAGES/seasons.po
    languages_mapping:
      two_letters_code:
        es: es
        fr: fr
        de: de
        it: it
        pt: pt
        pl: pl
        uk: uk
        zh: zh
        ja: ja
        ko: ko




