project_id: jarvisdiscordbot

files:
  - source: /skysearch/locales/messages.pot
    translation: /skysearch/locales/%locale%.po

  # Add more cogs with locales as needed
  # - source: /other_cog/locales/messages.json
  #   translation: /other_cog/locales/%locale_with_underscore%/LC_MESSAGES/messages.json
  #   type: json

